### ISSUE TITLE
hash # in url is ignored

### ISSUE THREAD

**Issue by Zitronella** [UnCrevard/LoadTabOnSelect-Evolution#2]
If i select with middleclick (mousewheel) or from contextmenu -> "open Link in new tab" a link  with a # in url, then the part after # is ignored.

For example https://www.camp-firefox.de/forum/viewtopic.php?f=16&t=125502#p1086433 this link open only  https://www.camp-firefox.de/forum/viewtopic.php?f=16&t=125502 

With extensionLoadTabOnSelect  https://addons.mozilla.org/en-US/firefox/addon/loadtabonselect/ it works correct, but this extension does not show the favicon on unload tab. This is the reason, i prefer your extension.

**Comment by UnCrevard** [comment]
Thanks for your report.

I will release soon a new version with better title & favicon support and I'll try to fix this bug.

Don't understand why Firefox removes the part after the # with window.location or the fetch function... Another mystery 😊 it sounds like it's a bad idea to use # in urls...

I'm working on it. 

https://stackoverflow.com/questions/18882857/hashtags-in-url-encoded-parameters-decoded-on-redirect#18889314

https://stackoverflow.com/questions/9319656/how-to-encode-a-path-that-contains-a-hash

**Comment by j-cr** [comment]
Looks like it's fixed in the latest version, no? Thanks! :P

**Comment by UnCrevard** [comment]
yes it works now 😊
