### ISSUE TITLE
Truncates URL containing "?url="

### ISSUE THREAD

**Issue by AirQuick** [UnCrevard/LoadTabOnSelect-Evolution#3]
#### Steps to repro
1. Enable LoadTabOnSelect-Evolution 1.4 on Firefox 61.0.1.
1. Open the attached HTML.
[test.zip](https://github.com/UnCrevard/LoadTabOnSelect-Evolution/files/2212357/test.zip)

1. Open the `test` link in a new tab and focus it.

#### Problem
The new tab loads `http://www.example.com/`.

#### Expected
`http://www.example.com/?url=test`

**Comment by UnCrevard** [comment]
Yes I see the problem. But I've changed the codebase so things are handled differently and this bug is gone now.

Will be fixed in the next release. Thanks for your report anyway 😃

**Comment by AirQuick** [comment]
Glad you've already fix it. 👍 

Will you be able to complete the next release soon?
I'm experiencing this issue and #2 frequently. The new release with them fixed is most welcome.
